version: "3"
services:
  zfile:
    image: stilleshan/zfile
    container_name: zfile
    ports:
      - 8080:8080
    volumes:
      - ./conf:/root/.zfile
      - ./data:/root/zfile/data
    restart: always

