version: '3.7'
services:
  v2-ui:
    image: stilleshan/v2-ui
    container_name: v2-ui
    volumes:
      - ./data/v2-ui.db:/etc/v2-ui/v2-ui.db
      - ./ssl:/ssl
    restart: always
    network_mode: host

  acme:
    image: neilpang/acme.sh
    container_name: acme
    volumes:
      - ./conf:/conf
      - ./ssl:/ssl
    restart: always
    network_mode: host
    command: ["sh", "-c", "/conf/start.sh"]
